name: Deploy Pulumi Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Login to Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Select stack
        run: pulumi stack select dev

      - name: Deploy infrastructure
        run: pulumi up --yes
